### PR TITLE
Added new from_hash feature and fixed the documentation.

### PR DESCRIPTION
**Pull request by ibarrajo**
I did multiple changes on the project.
- Fixed the documentation in the README.md and added tons of markdown.
- Created demo directory with the page from: http://www.checkman.io/please/
- Added a new feature that maps any string to the same color every time. (useful for use with ChartJS)

### CODE REVIEW

**Comment by ibarrajo** [comment]
I missed to comment-out a console.log on line 253, once it's merged can @Fooidge patch it?

**Comment by ibarrajo** [comment]
My fork has diverged quite a bit, it's still 100% compatible, but the patch files are huge.

I added a GulpJS build script and cleaned up the code to pass JSHint.

@Fooidge Tell me if you're interested in merging it.
https://github.com/ibarrajo/PleaseJS

**Comment by Fooidge** [comment]
I've been away for bit. Had some opportunities come up in large part due to the overwhelming response to Please.

I'd love it if you could reopen your branch.  I have some changes I'd like to make but a great deal of it will certainly go in.

Thanks a bunch,
Jordan

**Comment by ibarrajo** [comment]
Ok, I see there are some merge conflicts, I'll get to them later this afternoon.

**Comment by MaciekBaron** [comment]
I've already implemented seed based generation and my pull request is waiting, not sure which solution is better though.

EDIT:
To be honest I think my solution is a bit simpler and can be easily applied to generate any value without creating a separate case for it. But Fooidge can decide.

**Pull request closed without merging**
